
# Naive Baye's Machine Learning Algorithms Implementation

In [43]:
from sklearn.datasets import load_iris

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X,y=load_iris(return_X_y=True)

In [46]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [47]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [48]:
x_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [49]:
from sklearn.naive_bayes import GaussianNB
gnb=  GaussianNB()
gnb.fit(x_train,y_train)


GaussianNB()

In [50]:
y_pred =gnb.predict(x_test)

In [51]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [52]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [53]:
import seaborn as sns

In [54]:
df  = sns.load_dataset('tips')

In [55]:
df.head(

)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [56]:
df.iloc[:,:-2:]

total_bill   tip     sex smoker   day
0         16.99  1.01  Female     No   Sun
1         10.34  1.66    Male     No   Sun
2         21.01  3.50    Male     No   Sun
3         23.68  3.31    Male     No   Sun
4         24.59  3.61  Female     No   Sun
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No   Sat
240       27.18  2.00  Female    Yes   Sat
241       22.67  2.00    Male    Yes   Sat
242       17.82  1.75    Male     No   Sat
243       18.78  3.00  Female     No  Thur

[244 rows x 5 columns]

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns = 'time'),df['time'],test_size = 0.25,random_state = 42)

In [58]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

x_train['sex'] = le1.fit_transform(x_train['sex'])
# x_train['time'] = le2.fit_transform(x_train['time'])
x_train['smoker'] = le3.fit_transform(x_train['smoker'])



x_test['sex'] = le1.transform(x_test['sex'])


# x_test['time'] = le2.transform(x_test['time'])
x_test['smoker'] = le3.transform(x_test['smoker'])

In [76]:
x_train

total_bill   tip  sex  smoker  day  size
115       17.31  3.50    0       0  Sun     2
181       23.33  5.65    1       1  Sun     2
225       16.27  2.50    0       1  Fri     2
68        20.23  2.01    1       0  Sat     2
104       20.92  4.08    0       0  Sat     2
..          ...   ...  ...     ...  ...   ...
106       20.49  4.06    1       1  Sat     2
14        14.83  3.02    0       0  Sun     2
92         5.75  1.00    0       1  Fri     2
179       34.63  3.55    1       1  Sun     2
102       44.30  2.50    0       1  Sat     3

[183 rows x 6 columns]

In [82]:
# one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct  = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop = 'first'),[4])],remainder='passthrough')



import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
x_train = ct.fit_transform(x_train)
x_test = ct.transform(x_test)

In [84]:
x_train

array([[0.0, 1.0, 0.0, 0.0, 17.31, 3.5, 0, 2],
       [0.0, 1.0, 0.0, 1.0, 23.33, 5.65, 1, 2],
       [0.0, 0.0, 0.0, 1.0, 16.27, 2.5, 0, 2],
       [1.0, 0.0, 0.0, 0.0, 20.23, 2.01, 1, 2],
       [1.0, 0.0, 0.0, 0.0, 20.92, 4.08, 0, 2],
       [1.0, 0.0, 0.0, 1.0, 15.01, 2.09, 1, 2],
       [1.0, 0.0, 0.0, 0.0, 7.25, 1.0, 0, 1],
       [1.0, 0.0, 0.0, 1.0, 26.59, 3.41, 1, 3],
       [0.0, 1.0, 0.0, 0.0, 24.52, 3.48, 1, 3],
       [0.0, 1.0, 0.0, 0.0, 19.77, 2.0, 1, 4],
       [1.0, 0.0, 0.0, 1.0, 28.15, 3.0, 1, 5],
       [0.0, 0.0, 1.0, 0.0, 17.29, 2.71, 1, 2],
       [1.0, 0.0, 0.0, 0.0, 19.65, 3.0, 0, 2],
       [1.0, 0.0, 0.0, 1.0, 15.53, 3.0, 1, 2],
       [1.0, 0.0, 0.0, 0.0, 20.45, 3.0, 1, 4],
       [0.0, 1.0, 0.0, 1.0, 34.65, 3.68, 1, 4],
       [0.0, 1.0, 0.0, 0.0, 25.29, 4.71, 1, 4],
       [1.0, 0.0, 0.0, 1.0, 38.01, 3.0, 1, 4],
       [0.0, 0.0, 1.0, 0.0, 29.8, 4.2, 0, 6],
       [0.0, 0.0, 1.0, 0.0, 9.78, 1.73, 1, 2],
       [0.0, 1.0, 0.0, 0.0, 25.71, 4.0, 0, 3],
      

In [94]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,CategoricalNB,ComplementNB
gnb=  GaussianNB()
gnb.fit(x_train,y_train)


GaussianNB()

In [92]:
y_pred1 = gnb.predict(x_test)
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))
print(classification_report(y_pred1,y_test))

[[41  0]
 [ 3 17]]
0.9508196721311475
              precision    recall  f1-score   support

      Dinner       0.93      1.00      0.96        41
       Lunch       1.00      0.85      0.92        20

    accuracy                           0.95        61
   macro avg       0.97      0.93      0.94        61
weighted avg       0.95      0.95      0.95        61



In [96]:
mnb= MultinomialNB()
mnb.fit(x_train,y_train)
y_pred2 = mnb.predict(x_test)
print(confusion_matrix(y_pred2,y_test))
print(accuracy_score(y_pred2,y_test))
print(classification_report(y_pred2,y_test))

[[44  0]
 [ 0 17]]
1.0
              precision    recall  f1-score   support

      Dinner       1.00      1.00      1.00        44
       Lunch       1.00      1.00      1.00        17

    accuracy                           1.00        61
   macro avg       1.00      1.00      1.00        61
weighted avg       1.00      1.00      1.00        61



In [98]:
cnb= CategoricalNB()
cnb.fit(x_train,y_train)
y_pred3 = cnb.predict(x_test)
print(confusion_matrix(y_pred3,y_test))
print(accuracy_score(y_pred3,y_test))
print(classification_report(y_pred3,y_test))

[[44  0]
 [ 0 17]]
1.0
              precision    recall  f1-score   support

      Dinner       1.00      1.00      1.00        44
       Lunch       1.00      1.00      1.00        17

    accuracy                           1.00        61
   macro avg       1.00      1.00      1.00        61
weighted avg       1.00      1.00      1.00        61



In [100]:
ccnb= ComplementNB()
ccnb.fit(x_train,y_train)
y_pred4 = ccnb.predict(x_test)
print(confusion_matrix(y_pred4,y_test))
print(accuracy_score(y_pred4,y_test))
print(classification_report(y_pred4,y_test))

[[43  0]
 [ 1 17]]
0.9836065573770492
              precision    recall  f1-score   support

      Dinner       0.98      1.00      0.99        43
       Lunch       1.00      0.94      0.97        18

    accuracy                           0.98        61
   macro avg       0.99      0.97      0.98        61
weighted avg       0.98      0.98      0.98        61

